### ISSUE TITLE
iOS Performance is Slow

### ISSUE THREAD

**Issue by travisoneill** [IsenrichO/IsenrichO.github.io#1]
Initial loading time very slow and doesn't render fast enough to keep up with scroll speed. Seemed to be fine on Android.

**Comment by IsenrichO** [comment]
I believe it. I might need your help optimizing images bc that's definitely
a big part of it. Might have to use cloudnary after all.

<http://www.mulesoft.com/>
*Oliver Isenrich*

*Full-Stack Developer*

*w:* isenrich.io
*m:* (919) 741-3003
[image: GitHub Portfolio] <https://github.com/IsenrichO> *[image: LinkedIn
Profile] <https://www.linkedin.com/in/isenricholiver> *
<https://angel.co/isenricho> *[image: Facebook Profile]
<https://www.facebook.com/rE.vilO.I.13> **[image: Twitter Profile]
<https://twitter.com/IsenrichO> [image: Skype Profile]*

**Comment by IsenrichO** [comment]
Load time reportedly improved. Reported by @travisoneill
